### ISSUE TITLE
Invalid response from node

### ISSUE THREAD

**Issue by joshirio** [SemkoDev/field.cli#25] opened 2018-02-27 17:37 UTC
I'm trying to use [smidgen](https://github.com/bitfinexcom/smidgen) multisig tool from bitfinex and when using carriota field as the node provider, it is not able to handle the response. When using other nodes like `https://nodes.thetangle.org:443` everything is fine.

```
$ smidgen get-balance "XFAELMMFKBKNGAYLKNFOLHMOTAM9IVOLABDLNKNWUIFK9QJXEJKGAUHMEPMYPGLPFBWZAXJMFZYCWMQEAFMGNQKVFZ" --provider "https://field.carriota.com:443"
ERR! Received invalid response from node. 
ERR! Retry command or try to use another node. 
ERR! 
ERR! Use --provider to switch node.
```

```
$ smidgen get-balance "XFAELMMFKBKNGAYLKNFOLHMOTAM9IVOLABDLNKNWUIFK9QJXEJKGAUHMEPMYPGLPFBWZAXJMFZYCWMQEAFMGNQKVFZ" --provider "https://nodes.thetangle.org:443"
Balance: 218884849054300 (218884849.0543 Mi)
```

Is it possible that your response it not standard compliant?
Or maybe it is a bug on smidgen's side, although I read others having similar issues with different tools...

**Comment by joshirio** [comment] 2018-02-28 08:35
Another example is the [isf-jclient ](https://github.com/mikrohash/isf-jclient)from iotaspam.com

`[2018-02-28 09:33:16] [NodeMngr] [DBG] node 'https://field.carriota.com:443' [0] is not synced (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target), changing node to 'http://127.0.0.1:14265'`

**Comment by m1ndgames** [comment] 2018-02-28 15:05
Afaik the golang module also does it, but its not a bug, but a feature ;)
The Cert chain is missing, see: https://www.ssllabs.com/ssltest/analyze.html?d=field.carriota.com&s=216.58.194.211

Or verify yourself:
openssl s_client -showcerts -connect field.carriota.com:443

**Comment by romansemko** [comment] 2018-03-11 11:50
This should be fixed now. Added the correct SLL certificates chain to the load balancer.

**Closed by romansemko** 2018-03-11 11:50 UTC

**Comment by joshirio** [comment] 2018-03-11 15:40
Thank you, works now!
